apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: api-proxy
type: Opaque
data:
  MONGO_PASSWORD: ZXhhbXBsZQ==
  MONGO_USERNAME: cm9vdA== #root

---
apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: api-proxy
type: Opaque
data:
  API_KEY: YXBpLWtleQ== #api-key
