apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: Deployment
    name: api-proxy
  path: patch.yaml
- target:
    kind: Deployment  
    name: mongodb
  path: mongo-patch.yaml

namespace: api-proxy
